export const SIDE_MENU_SHOW_BLOCKS = 'SIDE_MENU_SHOW_BLOCKS'
export const SIDE_MENU_SHOW_FIELDS = 'SIDE_MENU_SHOW_FIELDS'

export const SELECT_FOR_DRAGGING = 'SELECT_FOR_DRAGGING'
export const UNSELECT_FOR_DRAGGING = 'UNSELECT_FOR_DRAGGING'

export const ADD_ITEM_TO_EDITOR = 'ADD_ITEM_TO_EDITOR'
export const DELETE_ITEM_FROM_EDITOR = 'DELETE_ITEM_FROM_EDITOR'

export const SELECT_FOR_EDITING = 'SELECT_FOR_EDITING'
export const UNSELECT_FROM_EDITING = 'UNSELECT_FROM_EDITING'